Repository CliMA/ClimaLand.jl, pull requests merged in 2024-01, with the labels that each got.

#447 update TagBot release notes
  .github/workflows/TagBot.yml
Labels: documentation

#448 default initialize_drivers
  src/shared_utilities/drivers.jl
Labels: bugfix

#441 Add a lib folder containing packages extending ClimaLSM functionality
  .buildkite/pipeline.yml
  lib/ClimaLandSimulations/LICENSE
  lib/ClimaLandSimulations/Project.toml
  lib/ClimaLandSimulations/README.md
  lib/ClimaLandSimulations/experiments/README.md
  lib/ClimaLandSimulations/experiments/ozark.jl
  lib/ClimaLandSimulations/src/ClimaLandSimulations.jl
  lib/ClimaLandSimulations/src/fluxnet/US-Ha1/US-Ha1_parameters.jl
  lib/ClimaLandSimulations/src/fluxnet/US-Ha1/US-Ha1_simulation.jl
  lib/ClimaLandSimulations/src/fluxnet/US-MOz/US-MOz_parameters.jl
  lib/ClimaLandSimulations/src/fluxnet/US-MOz/US-MOz_simulation.jl
  lib/ClimaLandSimulations/src/fluxnet/US-NR1/US-NR1_parameters.jl
  lib/ClimaLandSimulations/src/fluxnet/US-NR1/US-NR1_simulation.jl
  lib/ClimaLandSimulations/src/fluxnet/US-Var/US-Var_parameters.jl
  lib/ClimaLandSimulations/src/fluxnet/US-Var/US-Var_simulation.jl
  lib/ClimaLandSimulations/src/fluxnet_simulation.jl
  lib/ClimaLandSimulations/src/utilities/climalsm_output_dataframe.jl
  lib/ClimaLandSimulations/src/utilities/data_tools.jl
  lib/ClimaLandSimulations/src/utilities/domain_setup.jl
  lib/ClimaLandSimulations/src/utilities/inputs_dataframe.jl
  lib/ClimaLandSimulations/src/utilities/makie_plots.jl
  lib/ClimaLandSimulations/src/utilities/met_drivers_FLUXNET.jl
  lib/ClimaLandSimulations/src/utilities/pull_MODIS.jl
  lib/ClimaLandSimulations/src/utilities/timestepper_setup.jl
  lib/ClimaLandSimulations/test/runtests.jl
  lib/README.md
Labels: enhancement, API

#460 dependency updates
  .github/workflows/ci.yml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  experiments/Manifest.toml
  experiments/Project.toml
  lib/ClimaLandSimulations/Project.toml
  parameters/create_parameters.jl
  test/Project.toml
Labels: enhancement

#451 Remove splines, add `TimeVaryingInput`s
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/src/APIs/SoilBiogeochemistry.md
  docs/src/APIs/shared_utilities.md
  docs/src/Contributing.md
  docs/src/folderstructure.md
  docs/tutorials/integrated/soil_canopy_tutorial.jl
  docs/tutorials/shared_utilities/driver_tutorial.jl
  docs/tutorials/standalone/Bucket/bucket_tutorial.jl
  docs/tutorials/standalone/Canopy/canopy_tutorial.jl
  docs/tutorials/standalone/Usage/domain_tutorial.jl
  docs/tutorials/standalone/Usage/model_tutorial.jl
  experiments/Manifest.toml
  experiments/Project.toml
  experiments/integrated/fluxnet/met_drivers_FLUXNET.jl
  experiments/integrated/fluxnet/run_fluxnet.jl
  experiments/integrated/ozark/conservation/ozark_conservation.jl
  experiments/standalone/Biogeochemistry/experiment.jl
  experiments/standalone/Soil/evaporation.jl
  lib/ClimaLandSimulations/Project.toml
  lib/ClimaLandSimulations/src/ClimaLandSimulations.jl
  lib/ClimaLandSimulations/src/fluxnet_simulation.jl
  lib/ClimaLandSimulations/src/utilities/met_drivers_FLUXNET.jl
  src/ClimaLSM.jl
  src/shared_utilities/TimeVaryingInputs.jl
  src/shared_utilities/analytic_time_varying_input.jl
  src/shared_utilities/drivers.jl
  src/shared_utilities/general_utils.jl
  src/shared_utilities/interpolating_time_varying_input0d.jl
  src/shared_utilities/interpolating_time_varying_inputs.jl
  src/standalone/Soil/Biogeochemistry/Biogeochemistry.jl
  src/standalone/Soil/boundary_conditions.jl
  src/standalone/Vegetation/PlantHydraulics.jl
  test/integrated/soil_energy_hydrology_biogeochemistry.jl
  test/runtests.jl
  test/shared_utilities/drivers.jl
  test/shared_utilities/time_varying_inputs.jl
  test/shared_utilities/utilities.jl
  test/standalone/Bucket/albedo_types.jl
  test/standalone/Bucket/snow_bucket_tests.jl
  test/standalone/Bucket/soil_bucket_tests.jl
  test/standalone/Soil/Biogeochemistry/biogeochemistry_module.jl
  test/standalone/Soil/climate_drivers.jl
  test/standalone/Vegetation/canopy_model.jl
  test/standalone/Vegetation/plant_hydraulics_test.jl
Labels: enhancement, GPU, API, breaking change

#453 Move driver interface code from the Coupler to ClimaLSM
  docs/src/APIs/canopy/Canopy.md
  docs/src/APIs/shared_utilities.md
  docs/tutorials/standalone/Bucket/bucket_tutorial.jl
  docs/tutorials/standalone/Bucket/coupled_bucket.jl
  src/shared_utilities/drivers.jl
  src/standalone/Bucket/Bucket.jl
  src/standalone/Bucket/bucket_parameterizations.jl
  src/standalone/Soil/Soil.jl
  src/standalone/Soil/boundary_conditions.jl
  src/standalone/Soil/energy_hydrology.jl
  src/standalone/Vegetation/canopy_boundary_fluxes.jl
  test/standalone/Bucket/snow_bucket_tests.jl
  test/standalone/Bucket/soil_bucket_tests.jl
  test/standalone/Vegetation/canopy_model.jl
Labels: AMIP, breaking change
