Repository CliMA/ClimaLand.jl, pull requests merged in 2024-02, with the labels that each got.

#452 accommodate files containing multiple vars
  Project.toml
  docs/src/APIs/Regridder.md
  src/shared_utilities/FileReader.jl
  src/shared_utilities/Regridder.jl
  src/standalone/Bucket/Bucket.jl
  test/Project.toml
  test/artifacts/artifacts.jl
  test/runtests.jl
  test/shared_utilities/file_reader.jl
  test/shared_utilities/regridder.jl
  test/standalone/Bucket/albedo_types.jl
Labels: enhancement, API

#484 store bareground albedo
  docs/src/APIs/Bucket.md
  docs/tutorials/standalone/Bucket/bucket_tutorial.jl
  experiments/standalone/Bucket/compare_gpu_cpu_output.jl
  experiments/standalone/Bucket/global_bucket.jl
  src/shared_utilities/drivers.jl
  src/standalone/Bucket/Bucket.jl
  test/standalone/Bucket/albedo_types.jl
  test/standalone/Bucket/snow_bucket_tests.jl
  test/standalone/Bucket/soil_bucket_tests.jl
Labels: breaking change, bugfix

#485 SpaceVaryingInput
  docs/make.jl
  docs/src/APIs/shared_utilities.md
  docs/tutorials/integrated/soil_canopy_tutorial.jl
  docs/tutorials/standalone/Soil/freezing_front.jl
  docs/tutorials/standalone/Soil/layered_soil.jl
  docs/tutorials/standalone/Soil/richards_equation.jl
  docs/tutorials/standalone/Soil/soil_energy_hydrology.jl
  docs/tutorials/standalone/Usage/LSM_single_column_tutorial.jl
  docs/tutorials/standalone/Usage/model_tutorial.jl
  experiments/integrated/fluxnet/run_fluxnet.jl
  experiments/integrated/ozark/conservation/ozark_conservation.jl
  experiments/standalone/Biogeochemistry/experiment.jl
  experiments/standalone/Soil/evaporation.jl
  experiments/standalone/Soil/richards_comparison.jl
  experiments/standalone/Soil/water_conservation.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-Ha1/US-Ha1_parameters.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-MOz/US-MOz_parameters.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-NR1/US-NR1_parameters.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-Var/US-Var_parameters.jl
  src/ClimaLand.jl
  src/shared_utilities/SpaceVaryingInputs.jl
  src/shared_utilities/TimeVaryingInputs.jl
  src/shared_utilities/general_utils.jl
  src/shared_utilities/interpolating_time_varying_input0d.jl
  src/standalone/Bucket/Bucket.jl
  src/standalone/Soil/boundary_conditions.jl
  src/standalone/Soil/energy_hydrology.jl
  src/standalone/Soil/retention_models.jl
  src/standalone/Soil/rre.jl
  test/integrated/pond_soil_lsm.jl
  test/integrated/soil_energy_hydrology_biogeochemistry.jl
  test/runtests.jl
  test/shared_utilities/implicit_timestepping/richards_model.jl
  test/shared_utilities/space_varying_inputs.jl
  test/standalone/Bucket/albedo_types.jl
  test/standalone/Soil/climate_drivers.jl
  test/standalone/Soil/soil_bc.jl
  test/standalone/Soil/soil_parameterizations.jl
  test/standalone/Soil/soil_test_3d.jl
  test/standalone/Soil/soiltest.jl
Labels: enhancement, breaking change

#497 negative snow/water test, beta
  src/standalone/Bucket/Bucket.jl
  src/standalone/Bucket/bucket_parameterizations.jl
  test/standalone/Bucket/snow_bucket_tests.jl
Labels: enhancement

#474 Documentation of standalone models
  docs/list_standalone_models.jl
  docs/make.jl
  docs/src/standalone/README.md
  docs/src/standalone/apps.jl
  docs/src/standalone/apps/beer.jl
  docs/src/standalone/apps/hetero_resp.jl
  docs/src/standalone/apps/leaf_an.jl
  docs/src/standalone/apps/leaf_an_ci.jl
  docs/src/standalone/pages/snow/snow_model.md
  docs/src/standalone/pages/soil/biogeochemistry/DAMM_model.md
  docs/src/standalone/pages/soil/energy/energy_model.md
  docs/src/standalone/pages/soil/hydrology/richards_model.md
  docs/src/standalone/pages/surface_water/surface_water_model.md
  docs/src/standalone/pages/vegetation/photosynthesis/farquhar_model.md
  docs/src/standalone/pages/vegetation/photosynthesis/optimality_model.md
  docs/src/standalone/pages/vegetation/plant_hydraulics/van_genuchten_model.md
  docs/src/standalone/pages/vegetation/radiative_transfer/beer_model.md
  docs/src/standalone/pages/vegetation/radiative_transfer/twostream_model.md
  docs/src/standalone/pages/vegetation/stomatal_conductance/medlyn_model.md
Labels: documentation

#513 Bucket albedo parameterization cleanup
  docs/Manifest.toml
  docs/src/APIs/Bucket.md
  docs/tutorials/standalone/Bucket/bucket_tutorial.jl
  experiments/standalone/Bucket/global_bucket_function.jl
  experiments/standalone/Bucket/global_bucket_staticmap.jl
  experiments/standalone/Bucket/global_bucket_temporalmap.jl
  src/standalone/Bucket/Bucket.jl
  test/standalone/Bucket/albedo_types.jl
  test/standalone/Bucket/snow_bucket_tests.jl
  test/standalone/Bucket/soil_bucket_tests.jl
Labels: breaking change
