Repository CliMA/ClimaLand.jl, pull requests merged in 2024-05, with the labels that each got.

#577 Global bucket model simulation with ERA5 forcing
  experiments/Artifacts.toml
  experiments/Manifest.toml
  experiments/standalone/Bucket/global_bucket_staticmap.jl
  experiments/standalone/Soil/Artifacts.toml
  experiments/standalone/Soil/richards_runoff.jl
Labels: LSMv1, GPU

#565 Paper plots
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/APIs/shared_utilities.md
  docs/tutorials/standalone/Soil/evaporation.jl
  docs/tutorials/standalone/Soil/evaporation_gilat_loess.jl
  docs/tutorials/standalone/Soil/freezing_front.jl
  src/integrated/soil_canopy_model.jl
  src/shared_utilities/Domains.jl
  src/shared_utilities/boundary_conditions.jl
  src/standalone/Soil/Biogeochemistry/Biogeochemistry.jl
  src/standalone/Soil/boundary_conditions.jl
  src/standalone/Soil/energy_hydrology.jl
  src/standalone/Soil/rre.jl
  test/standalone/Soil/climate_drivers.jl
  test/standalone/Soil/soil_bc.jl
Labels: documentation, enhancement, bugfix

#147 Snow model RHS functions
  .buildkite/pipeline.yml
  README.md
  docs/src/APIs/Snow.md
  experiments/standalone/Snow/process_cdp.jl
  experiments/standalone/Snow/snow_cdp.jl
  src/standalone/Snow/Snow.jl
  src/standalone/Snow/snow_parameterizations.jl
  test/runtests.jl
  test/standalone/Snow/parameterizations.jl
  test/standalone/Snow/snow.jl
Labels: LSMv1

#592 Add benchmark pipeline
  .buildkite/pipeline.yml
  .buildkite/target/pipeline.yml
  Project.toml
  experiments/benchmarks/bucket.jl
Labels: Run benchmarks
