Repository CliMA/ClimaLand.jl, pull requests merged in 2024-04, with the labels that each got.

#561 Add profiling of the land surface model.
  .buildkite/pipeline.yml
  .gitignore
  NEWS.md
  experiments/integrated/ozark/conservation/ozark_simulation.jl
  experiments/integrated/performance/conservation/ozark_conservation.jl
  experiments/integrated/performance/conservation/ozark_conservation_setup.jl
  experiments/integrated/performance/profile_allocations.jl
  experiments/standalone/Bucket/global_bucket_function.jl
  experiments/standalone/Bucket/global_bucket_staticmap.jl
  experiments/standalone/Bucket/global_bucket_temporalmap.jl
  src/integrated/soil_canopy_model.jl
  src/shared_utilities/drivers.jl
  src/shared_utilities/utils.jl
Labels: enhancement

#576 Convert ld to Function type and Parameterize by Leaf Orientation Index
  docs/tutorials/integrated/soil_canopy_tutorial.jl
  docs/tutorials/standalone/Canopy/canopy_tutorial.jl
  experiments/integrated/fluxnet/US-Ha1/US-Ha1_parameters.jl
  experiments/integrated/fluxnet/US-MOz/US-MOz_parameters.jl
  experiments/integrated/fluxnet/US-NR1/US-NR1_parameters.jl
  experiments/integrated/fluxnet/US-Var/US-Var_parameters.jl
  experiments/integrated/fluxnet/ozark_pft.jl
  experiments/integrated/fluxnet/run_fluxnet.jl
  experiments/integrated/performance/conservation/ozark_conservation_setup.jl
  ext/CreateParametersExt.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-Ha1/US-Ha1_parameters.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-MOz/US-MOz_parameters.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-NR1/US-NR1_parameters.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-Var/US-Var_parameters.jl
  lib/ClimaLandSimulations/src/Fluxnet/run_fluxnet.jl
  src/standalone/Vegetation/Canopy.jl
  src/standalone/Vegetation/canopy_parameterizations.jl
  src/standalone/Vegetation/radiation.jl
  test/standalone/Vegetation/test_bigleaf_parameterizations.jl
  test/standalone/Vegetation/test_two_stream.jl
Labels: enhancement, breaking change

#494 ClimaLandSimulations make all figures of experiments
  .github/workflows/ClimaLandSimulations.yml
  NEWS.md
  lib/ClimaLandSimulations/README.md
  lib/ClimaLandSimulations/experiments/ozark.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-Ha1/US-Ha1_config.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-Ha1/US-Ha1_simulation.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-MOz/US-MOz_config.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-MOz/US-MOz_simulation.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-NR1/US-NR1_config.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-NR1/US-NR1_simulation.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-Var/US-Var_config.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_sites/US-Var/US-Var_simulation.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_utilities/make_config.jl
  lib/ClimaLandSimulations/src/Fluxnet/fluxnet_utilities/make_setup.jl
  lib/ClimaLandSimulations/src/utilities/climaland_output_dataframe.jl
  lib/ClimaLandSimulations/src/utilities/make_timestepper.jl
  lib/ClimaLandSimulations/src/utilities/makie_plots.jl
  lib/ClimaLandSimulations/test/Project.toml
  lib/ClimaLandSimulations/test/runtests.jl
Labels: documentation, Continuous integration :gear:, API
