Repository CliMA/ClimaLand.jl, pull requests merged in 2024-03, with the labels that each got.

#535 Refactor boundary condition types
  docs/make.jl
  docs/src/APIs/Soil.md
  docs/src/APIs/shared_utilities.md
  docs/tutorials/integrated/soil_canopy_tutorial.jl
  docs/tutorials/standalone/Soil/boundary_conditions.jl
  docs/tutorials/standalone/Soil/freezing_front.jl
  docs/tutorials/standalone/Soil/layered_soil.jl
  docs/tutorials/standalone/Soil/richards_equation.jl
  docs/tutorials/standalone/Soil/soil_energy_hydrology.jl
  docs/tutorials/standalone/Usage/LSM_single_column_tutorial.jl
  experiments/integrated/fluxnet/run_fluxnet.jl
  experiments/integrated/ozark/conservation/ozark_conservation.jl
  experiments/standalone/Biogeochemistry/experiment.jl
  experiments/standalone/Soil/evaporation.jl
  experiments/standalone/Soil/richards_comparison.jl
  experiments/standalone/Soil/water_conservation.jl
  lib/ClimaLandSimulations/src/Fluxnet/run_fluxnet.jl
  src/ClimaLand.jl
  src/integrated/pond_soil_model.jl
  src/integrated/soil_canopy_model.jl
  src/shared_utilities/boundary_conditions.jl
  src/standalone/Soil/Biogeochemistry/Biogeochemistry.jl
  src/standalone/Soil/boundary_conditions.jl
  src/standalone/Soil/energy_hydrology.jl
  src/standalone/Soil/rre.jl
  test/integrated/pond_soil_lsm.jl
  test/integrated/soil_energy_hydrology_biogeochemistry.jl
  test/shared_utilities/implicit_timestepping/richards_model.jl
  test/shared_utilities/variable_types.jl
  test/standalone/Soil/Biogeochemistry/biogeochemistry_module.jl
  test/standalone/Soil/climate_drivers.jl
  test/standalone/Soil/soil_bc.jl
  test/standalone/Soil/soil_test_3d.jl
  test/standalone/Soil/soiltest.jl
Labels: documentation, API, breaking change

#478 Web dashboard for FLUXNET simulations O2.4.5
  lib/ClimaLandSimulations/Project.toml
  lib/ClimaLandSimulations/experiments/.ozark.jl.swo
  lib/ClimaLandSimulations/experiments/.ozark.jl.swp
  lib/ClimaLandSimulations/src/ClimaLandSimulations.jl
  lib/ClimaLandSimulations/src/Dashboards/Dashboards.jl
  lib/ClimaLandSimulations/src/Dashboards/fluxnet_dashboard.jl
  lib/ClimaLandSimulations/src/utilities/makie_plots.jl
Labels: enhancement

#507 Refactor bucket parameters
  Project.toml
  docs/Manifest.toml
  docs/tutorials/standalone/Bucket/bucket_tutorial.jl
  experiments/Manifest.toml
  experiments/standalone/Bucket/global_bucket_function.jl
  experiments/standalone/Bucket/global_bucket_staticmap.jl
  experiments/standalone/Bucket/global_bucket_temporalmap.jl
  ext/CreateParametersExt.jl
  src/standalone/Bucket/Bucket.jl
  test/standalone/Bucket/albedo_types.jl
  test/standalone/Bucket/snow_bucket_tests.jl
  test/standalone/Bucket/soil_bucket_tests.jl
Labels: breaking change
